/** @type {import('tailwindcss').Config} */
module.exports = {
  theme: {
    extend: {
      colors: {
        'surface-page': '#FFFFFF',
        'surface-secondary': '#F7F7F5',
        'surface-soft-pink': '#FFF7F9',
        'surface-variant': '#e4e2e2',
        'surface-container': '#efeded',
        'surface-container-high': '#e9e8e7',
        'text-primary': '#171717',
        'text-secondary': '#6B6B6B',
        'text-muted': '#9A9A9A',
        'border-default': '#E8E8E8',
        'border-strong': '#D9D9D9',
        'primary-container': '#FFA8C5',
        'primary-hover': '#FF8FB5',
        'primary-pressed': '#E8759C',
        'primary-fixed': '#ffd9e3',
        'on-primary': '#ffffff',
        tertiary: '#9f3b60',
        'status-success': '#22A06B',
        'status-success-bg': '#EAF8F1',
        'status-warning': '#E9A23B',
        'status-warning-bg': '#FFF5E3',
        'status-error': '#D64545',
        'status-error-bg': '#FDECEC',
        'status-info': '#3B82F6',
        'status-info-bg': '#EFF6FF',
      },
      fontFamily: {
        headline: ['Manrope', 'system-ui', 'sans-serif'],
        body: ['Inter', 'system-ui', 'sans-serif'],
      },
      fontSize: {
        'headline-xl': ['56px', { lineHeight: '60px', letterSpacing: '-0.03em', fontWeight: '800' }],
        'headline-xl-mobile': ['34px', { lineHeight: '38px', letterSpacing: '-0.02em', fontWeight: '800' }],
        'headline-lg': ['36px', { lineHeight: '42px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'headline-lg-mobile': ['26px', { lineHeight: '32px', letterSpacing: '-0.01em', fontWeight: '700' }],
        'headline-md': ['24px', { lineHeight: '30px', letterSpacing: '-0.01em', fontWeight: '700' }],
        'headline-sm': ['20px', { lineHeight: '26px', fontWeight: '600' }],
        'body-lg': ['18px', { lineHeight: '28px', fontWeight: '400' }],
        'body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'body-sm': ['14px', { lineHeight: '20px', fontWeight: '400' }],
        'label-lg': ['16px', { lineHeight: '22px', fontWeight: '700' }],
        'label-md': ['14px', { lineHeight: '18px', fontWeight: '600' }],
        'label-sm': ['12px', { lineHeight: '16px', letterSpacing: '0.02em', fontWeight: '600' }],
      },
      spacing: {
        gutter: '1.5rem',
        'gutter-mobile': '1rem',
        margin: '2.5rem',
        'margin-mobile': '1.25rem',
        'space-xs': '0.25rem',
        'space-sm': '0.5rem',
        'space-md': '1rem',
        'space-lg': '1.5rem',
        'space-xl': '2rem',
        'space-2xl': '3rem',
        'space-3xl': '5rem',
      },
    },
  },
  plugins: [
    require('daisyui'),
  ],
  daisyui: {
    themes: ['light', 'dark', 'garden'],
  },
}